_BASE_: "../prima/fast_rcnn_R_50_FPN_3x.yaml"

MODEL:
  DEVICE: cpu  # Change to 'cuda' if you have GPU available
  ROI_HEADS:
    NUM_CLASSES: 1  # Only 'photo' class (change to 2 if you also labeled 'text')
  WEIGHTS: "detectron2://COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl"

SOLVER:
  IMS_PER_BATCH: 2  # Reduce to 1 if running out of memory
  BASE_LR: 0.00025  # Learning rate - can tune this
  MAX_ITER: 3000    # More iterations = better model (but longer training)
  STEPS: (2000, 2500)  # Learning rate decay steps
  CHECKPOINT_PERIOD: 500  # Save checkpoint every 500 iterations

INPUT:
  MIN_SIZE_TRAIN: (800,)  # Yearbook pages are typically large images
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

OUTPUT_DIR: "../outputs/yearbook/fast_rcnn_R_50_FPN_3x/"
